{{- if and .Values.secrets.values (not .Values.secrets.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "whatomate.secretName" . }}
  labels:
    {{- include "whatomate.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $path, $value := .Values.secrets.values }}
  {{ include "whatomate.envName" $path }}: {{ $value | toString | quote }}
  {{- end }}
{{- end }}
